# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
