version: '2'
services:
  web:
    build: .
    image: mymusic_base
    container_name: mymusic_web
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "8080:8080"
      - "22:22"
    links:
      - db
  db:
    image: postgres
    container_name: mymusic_db
    ports:
      - "5432:5432"
