# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistImage',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
