# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20161009_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
