# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='durantion',
            new_name='duration',
        ),
    ]
