# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20161010_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
